/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta "github.com/SunSince90/polycube-firewall-template/pkg/apis/polycubenetwork.com/v1beta"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFirewallTemplates implements FirewallTemplateInterface
type FakeFirewallTemplates struct {
	Fake *FakePolycubenetworkV1beta
	ns   string
}

var firewalltemplatesResource = schema.GroupVersionResource{Group: "polycubenetwork.com", Version: "v1beta", Resource: "firewalltemplates"}

var firewalltemplatesKind = schema.GroupVersionKind{Group: "polycubenetwork.com", Version: "v1beta", Kind: "FirewallTemplate"}

// Get takes name of the firewallTemplate, and returns the corresponding firewallTemplate object, and an error if there is any.
func (c *FakeFirewallTemplates) Get(name string, options v1.GetOptions) (result *v1beta.FirewallTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(firewalltemplatesResource, c.ns, name), &v1beta.FirewallTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.FirewallTemplate), err
}

// List takes label and field selectors, and returns the list of FirewallTemplates that match those selectors.
func (c *FakeFirewallTemplates) List(opts v1.ListOptions) (result *v1beta.FirewallTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(firewalltemplatesResource, firewalltemplatesKind, c.ns, opts), &v1beta.FirewallTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta.FirewallTemplateList{ListMeta: obj.(*v1beta.FirewallTemplateList).ListMeta}
	for _, item := range obj.(*v1beta.FirewallTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested firewallTemplates.
func (c *FakeFirewallTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(firewalltemplatesResource, c.ns, opts))

}

// Create takes the representation of a firewallTemplate and creates it.  Returns the server's representation of the firewallTemplate, and an error, if there is any.
func (c *FakeFirewallTemplates) Create(firewallTemplate *v1beta.FirewallTemplate) (result *v1beta.FirewallTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(firewalltemplatesResource, c.ns, firewallTemplate), &v1beta.FirewallTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.FirewallTemplate), err
}

// Update takes the representation of a firewallTemplate and updates it. Returns the server's representation of the firewallTemplate, and an error, if there is any.
func (c *FakeFirewallTemplates) Update(firewallTemplate *v1beta.FirewallTemplate) (result *v1beta.FirewallTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(firewalltemplatesResource, c.ns, firewallTemplate), &v1beta.FirewallTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.FirewallTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFirewallTemplates) UpdateStatus(firewallTemplate *v1beta.FirewallTemplate) (*v1beta.FirewallTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(firewalltemplatesResource, "status", c.ns, firewallTemplate), &v1beta.FirewallTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.FirewallTemplate), err
}

// Delete takes name of the firewallTemplate and deletes it. Returns an error if one occurs.
func (c *FakeFirewallTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(firewalltemplatesResource, c.ns, name), &v1beta.FirewallTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFirewallTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(firewalltemplatesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta.FirewallTemplateList{})
	return err
}

// Patch applies the patch and returns the patched firewallTemplate.
func (c *FakeFirewallTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta.FirewallTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(firewalltemplatesResource, c.ns, name, pt, data, subresources...), &v1beta.FirewallTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta.FirewallTemplate), err
}
