/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta

import (
	"time"

	v1beta "github.com/SunSince90/polycube-firewall-template/pkg/apis/polycubenetwork.com/v1beta"
	scheme "github.com/SunSince90/polycube-firewall-template/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FirewallTemplatesGetter has a method to return a FirewallTemplateInterface.
// A group's client should implement this interface.
type FirewallTemplatesGetter interface {
	FirewallTemplates(namespace string) FirewallTemplateInterface
}

// FirewallTemplateInterface has methods to work with FirewallTemplate resources.
type FirewallTemplateInterface interface {
	Create(*v1beta.FirewallTemplate) (*v1beta.FirewallTemplate, error)
	Update(*v1beta.FirewallTemplate) (*v1beta.FirewallTemplate, error)
	UpdateStatus(*v1beta.FirewallTemplate) (*v1beta.FirewallTemplate, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta.FirewallTemplate, error)
	List(opts v1.ListOptions) (*v1beta.FirewallTemplateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta.FirewallTemplate, err error)
	FirewallTemplateExpansion
}

// firewallTemplates implements FirewallTemplateInterface
type firewallTemplates struct {
	client rest.Interface
	ns     string
}

// newFirewallTemplates returns a FirewallTemplates
func newFirewallTemplates(c *PolycubenetworkV1betaClient, namespace string) *firewallTemplates {
	return &firewallTemplates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the firewallTemplate, and returns the corresponding firewallTemplate object, and an error if there is any.
func (c *firewallTemplates) Get(name string, options v1.GetOptions) (result *v1beta.FirewallTemplate, err error) {
	result = &v1beta.FirewallTemplate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("firewalltemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FirewallTemplates that match those selectors.
func (c *firewallTemplates) List(opts v1.ListOptions) (result *v1beta.FirewallTemplateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta.FirewallTemplateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("firewalltemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested firewallTemplates.
func (c *firewallTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("firewalltemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a firewallTemplate and creates it.  Returns the server's representation of the firewallTemplate, and an error, if there is any.
func (c *firewallTemplates) Create(firewallTemplate *v1beta.FirewallTemplate) (result *v1beta.FirewallTemplate, err error) {
	result = &v1beta.FirewallTemplate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("firewalltemplates").
		Body(firewallTemplate).
		Do().
		Into(result)
	return
}

// Update takes the representation of a firewallTemplate and updates it. Returns the server's representation of the firewallTemplate, and an error, if there is any.
func (c *firewallTemplates) Update(firewallTemplate *v1beta.FirewallTemplate) (result *v1beta.FirewallTemplate, err error) {
	result = &v1beta.FirewallTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("firewalltemplates").
		Name(firewallTemplate.Name).
		Body(firewallTemplate).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *firewallTemplates) UpdateStatus(firewallTemplate *v1beta.FirewallTemplate) (result *v1beta.FirewallTemplate, err error) {
	result = &v1beta.FirewallTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("firewalltemplates").
		Name(firewallTemplate.Name).
		SubResource("status").
		Body(firewallTemplate).
		Do().
		Into(result)
	return
}

// Delete takes name of the firewallTemplate and deletes it. Returns an error if one occurs.
func (c *firewallTemplates) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("firewalltemplates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *firewallTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("firewalltemplates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched firewallTemplate.
func (c *firewallTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta.FirewallTemplate, err error) {
	result = &v1beta.FirewallTemplate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("firewalltemplates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
