# Definition of the firewall template
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: firewalltemplates.polycubenetwork.com
spec:  
  group: polycubenetwork.com  
  version: v1beta
  scope: Namespaced  
  names:    
    kind: FirewallTemplate   
    shortNames: 
    - fwt
    plural: firewalltemplates
    singular: firewalltemplate